server:
  port: 9125

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price-tracker
    username: postgres
    password: Zk.,k.,juf7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
